### ISSUE TITLE
Unable to install f2f-app_0.1.0_x64.deb on Ubuntu 16.04 amd64 

### ISSUE THREAD

**Issue by HoldingHands** [USHIN-Inc/f2f-app#1]
When attempting to install https://github.com/hiimalexjgarcia/f2f-app/releases/download/v0.1.0/f2f-app_0.1.0_x64.deb on Ubuntu 16.04 amd64, I'm receiving the following error:

$ sudo dpkg -i f2f-app_0.1.0_x64.deb 
dpkg: error processing archive f2f-app_0.1.0_x64.deb (--install):
 package architecture (x64) does not match system (amd64)
Errors were encountered while processing:
 f2f-app_0.1.0_x64.deb

**Comment by hiimalexjgarcia** [comment]
We're still investigating the source of the issue, and have opted to abandon Debian x86/amd64 builds (as well as Windows x64 builds) for now. As of v0.1.1, we'll be releasing installer and portable builds for Windows x86 only.
